# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #DCDADE
background         #303030
cursor             #A19FA3

active_tab_foreground     #303030
active_tab_background     #DCDADE
inactive_tab_foreground   #DCDADE
inactive_tab_background   #303030

active_border_color   #DCDADE
inactive_border_color #303030
bell_border_color     #3F3D40

color0      #545454
color1		#3F3D40
color2		#4C4A4E
color3		#5A575D
color4		#67646B
color5		#757079
color6		#757079
color7		#C5C2C8
color8		#8A888C
color9		#545256
color10		#666369
color11		#78747B
color12		#8A858E
color13		#9C96A1
color14		#9C96A1
color15		#C5C2C8
