# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #BFD4BB
background         #252423
cursor             #AA8D80

active_tab_foreground     #252423
active_tab_background     #BFD4BB
inactive_tab_foreground   #BFD4BB
inactive_tab_background   #252423

active_border_color   #BFD4BB
inactive_border_color #252423
bell_border_color     #201A18

color0      #4B4949
color1		#201A18
color2		#703433
color3		#713330
color4		#5E3D5B
color5		#593F65
color6		#37642E
color7		#9CBA96
color8		#6D8269
color9		#2B2220
color10		#954544
color11		#974440
color12		#7D517A
color13		#775487
color14		#49853D
color15		#9CBA96
